# Generated by Django 5.0.6 on 2026-03-20 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mocktest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("study_time_minutes", models.IntegerField(default=0)),
                ("questions_attempted", models.IntegerField(default=0)),
                ("questions_correct", models.IntegerField(default=0)),
                ("mock_tests_taken", models.IntegerField(default=0)),
                ("ai_queries", models.IntegerField(default=0)),
                ("topics_covered", models.JSONField(blank=True, default=list)),
                ("streak_days", models.IntegerField(default=0)),
                ("goals_met", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_progress",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="daily_progr_user_id_9412c4_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(db_index=True, max_length=200)),
                ("total_attempts", models.IntegerField(default=0)),
                ("total_questions", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("incorrect_answers", models.IntegerField(default=0)),
                ("accuracy_percentage", models.FloatField(default=0.0)),
                ("average_score", models.FloatField(default=0.0)),
                ("total_time_minutes", models.IntegerField(default=0)),
                ("average_time_per_question", models.FloatField(default=0.0)),
                ("easy_accuracy", models.FloatField(default=0.0)),
                ("medium_accuracy", models.FloatField(default=0.0)),
                ("hard_accuracy", models.FloatField(default=0.0)),
                ("improvement_rate", models.FloatField(default=0.0)),
                ("consistency_score", models.FloatField(default=0.0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "performance_metrics",
                "ordering": ["-accuracy_percentage"],
                "unique_together": {("user", "subject")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(db_index=True, max_length=200)),
                ("score", models.FloatField()),
                ("total_marks", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "test_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to="mocktest.testattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "performance_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="performance_user_id_683e65_idx",
                    ),
                    models.Index(
                        fields=["subject"], name="performance_subject_6b85c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("roadmap", "Roadmap Study"),
                            ("mock_test", "Mock Test"),
                            ("practice", "Practice Questions"),
                            ("ai_chat", "AI Doubt Clearing"),
                            ("revision", "Revision"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("questions_attempted", models.IntegerField(default=0)),
                ("questions_correct", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "started_at"],
                        name="study_sessi_user_id_d89a4c_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="study_sessi_activit_2e8c5f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeakArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(db_index=True, max_length=200)),
                ("topic", models.CharField(db_index=True, max_length=200)),
                ("attempts", models.IntegerField(default=0)),
                ("correct", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(default=0.0)),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="1=High, 2=Medium, 3=Low"),
                ),
                ("is_improving", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weak_areas",
                "ordering": ["priority", "-accuracy"],
                "unique_together": {("user", "subject", "topic")},
            },
        ),
    ]
