# Generated by Django 5.2.11 on 2026-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('mock_tests_taken', models.IntegerField(default=0)),
                ('ai_queries', models.IntegerField(default=0)),
                ('topics_covered', models.JSONField(blank=True, default=list)),
                ('streak_days', models.IntegerField(default=0)),
                ('goals_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('average_time_per_question', models.FloatField(default=0.0)),
                ('easy_accuracy', models.FloatField(default=0.0)),
                ('medium_accuracy', models.FloatField(default=0.0)),
                ('hard_accuracy', models.FloatField(default=0.0)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-accuracy_percentage'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('roadmap', 'Roadmap Study'), ('mock_test', 'Mock Test'), ('practice', 'Practice Questions'), ('ai_chat', 'AI Doubt Clearing'), ('revision', 'Revision')], max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('attempts', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=1, help_text='1=High, 2=Medium, 3=Low')),
                ('is_improving', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weak_areas',
                'ordering': ['priority', '-accuracy'],
            },
        ),
    ]
