# Generated by Django 5.2.11 on 2026-02-05 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancemetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weakarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyprogress',
            index=models.Index(fields=['user', 'date'], name='daily_progr_user_id_9412c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprogress',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='performancemetrics',
            unique_together={('user', 'subject')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'started_at'], name='study_sessi_user_id_d89a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['activity_type'], name='study_sessi_activit_2e8c5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weakarea',
            unique_together={('user', 'subject', 'topic')},
        ),
    ]
