# Generated by Django 5.0.6 on 2026-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_topicperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicperformance",
            name="strength",
            field=models.CharField(
                choices=[
                    ("weak", "Weak"),
                    ("moderate", "Moderate"),
                    ("strong", "Strong"),
                    ("insufficient", "Insufficient Data"),
                ],
                db_index=True,
                default="insufficient",
                max_length=20,
            ),
        ),
    ]
