# Generated by Django 5.0.6 on 2026-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyprogress",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="performancemetrics",
            name="subject",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("roadmap", "Roadmap Study"),
                    ("mock_test", "Mock Test"),
                    ("practice", "Practice Questions"),
                    ("ai_chat", "AI Doubt Clearing"),
                    ("revision", "Revision"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="weakarea",
            name="subject",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="weakarea",
            name="topic",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
