# Generated by Django 5.0.6 on 2026-03-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_topicperformance_strength"),
        ("roadmap", "0030_alter_topic_weightage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyContentCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("youtube_links", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roadmap.topic"
                    ),
                ),
            ],
            options={
                "db_table": "study_content_cache",
                "unique_together": {("topic",)},
            },
        ),
    ]
