# Generated by Django 5.0.6 on 2026-03-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_studycontentcache"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="topicperformance",
            table="topic_performance",
        ),
    ]
