sonar.projectKey=MSKalyan_AI-Prep
sonar.organization=mskalyan

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=AI-Prep
#sonar.projectVersion=1.0

# Path is relative to this file.
sonar.sources=backend/apps
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/migrations/**,**/tests.py,**/conftest.py,**/__pycache__/**,**/*.pyc,**/test_*.py

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

