sonar.projectKey=MSKalyan_AI-Prep
sonar.organization=mskalyan

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=AI-Prep
#sonar.projectVersion=1.0

# Path is relative to this file.
sonar.sources=backend/apps
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=**/migrations/**,**/tests.py,**/conftest.py,**/__pycache__/**,**/*.pyc,**/test_*.py,backend/apps/roadmap/management/commands/**,backend/apps/roadmap/services/adaptive_service.py,backend/apps/roadmap/services/pyq/drive_downloader.py,backend/apps/roadmap/services/pyq/pyq_file_selector.py,backend/apps/roadmap/services/pyq/pyq_import_service.py,backend/apps/roadmap/services/pyq/pyq_text_extractor.py,backend/apps/roadmap/services/pyq/topic_mapper_service.py,backend/apps/roadmap/services/pyq/zip_extractor_service.py,backend/apps/roadmap/services/syllabus/pdf_downloader_service.py,backend/apps/roadmap/services/syllabus/pdf_text_extractor.py,backend/apps/roadmap/services/syllabus/scrape_gate_syllabus.py,backend/apps/roadmap/services/syllabus/syllabus_import_service.py,backend/apps/roadmap/services/syllabus/syllabus_parser_service.py,backend/apps/ai_service/rag/**,backend/apps/ai_service/services/llm_service.py

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
