# Generated by Django 5.0.6 on 2026-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_exam_remove_roadmap_exam_name_roadmap_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="roadmapgenerationjob",
            name="input_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="target_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="total_weeks",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="roadmapgenerationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roadmaptopic",
            name="estimated_hours",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name="roadmaptopic",
            unique_together={("roadmap", "week_number", "title")},
        ),
    ]
