# Generated by Django 5.0.6 on 2026-02-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_roadmap_is_active_roadmap_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="roadmap.exam",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="roadmap.topic",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["order", "name"],
                "unique_together": {("exam", "name")},
            },
        ),
    ]
