# Generated by Django 5.0.6 on 2026-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0005_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_core",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="pyq_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="total_marks",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="topic",
            name="weightage",
            field=models.FloatField(default=0.0),
        ),
    ]
