# Generated by Django 5.0.6 on 2026-02-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0006_topic_is_core_topic_pyq_count_topic_total_marks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PYQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("marks", models.FloatField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyqs",
                        to="roadmap.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyqs",
                        to="roadmap.topic",
                    ),
                ),
            ],
            options={
                "db_table": "pyqs",
                "indexes": [
                    models.Index(
                        fields=["exam", "year"], name="pyqs_exam_id_1c6dea_idx"
                    ),
                    models.Index(fields=["topic"], name="pyqs_topic_i_e5884d_idx"),
                ],
            },
        ),
    ]
