# Generated by Django 5.0.6 on 2026-02-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0007_pyq"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("exam", "parent", "name")},
        ),
    ]
