# Generated by Django 5.0.6 on 2026-03-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0008_alter_topic_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaptopic",
            name="phase",
            field=models.CharField(
                choices=[
                    ("coverage", "Coverage"),
                    ("practice", "Practice"),
                    ("revision", "Revision"),
                ],
                default="coverage",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
