# Generated by Django 5.0.6 on 2026-03-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0009_roadmaptopic_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaptopic",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_entries",
                to="roadmap.topic",
            ),
        ),
    ]
