# Generated by Django 5.0.6 on 2026-03-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0010_roadmaptopic_topic"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roadmaptopic",
            unique_together={("roadmap", "week_number", "topic")},
        ),
        migrations.AlterField(
            model_name="roadmaptopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_entries",
                to="roadmap.topic",
            ),
        ),
        migrations.RemoveField(
            model_name="roadmaptopic",
            name="description",
        ),
        migrations.RemoveField(
            model_name="roadmaptopic",
            name="title",
        ),
    ]
