# Generated by Django 5.0.6 on 2026-03-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0011_alter_roadmaptopic_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadmap",
            name="difficulty_level",
        ),
    ]
