# Generated by Django 5.0.6 on 2026-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0012_remove_roadmap_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
