# Generated by Django 5.0.6 on 2026-03-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0013_exam_exam_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="total_marks",
            new_name="pyq_total_marks",
        ),
    ]
