# Generated by Django 5.0.6 on 2026-03-04 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0014_rename_total_marks_topic_pyq_total_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(default=datetime.date(2026, 12, 12)),
            preserve_default=False,
        ),
    ]
