# Generated by Django 5.0.6 on 2026-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0015_alter_exam_exam_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaptopic",
            name="day_number",
            field=models.IntegerField(default=1),
        ),
    ]
