# Generated by Django 5.0.6 on 2026-03-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0016_roadmaptopic_day_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roadmaptopic",
            unique_together={("roadmap", "week_number", "day_number", "topic")},
        ),
    ]
