# Generated by Django 5.0.6 on 2026-03-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0017_alter_roadmaptopic_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaptopic",
            name="ai_explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
