# Generated by Django 5.0.6 on 2026-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0018_roadmaptopic_ai_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmap",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
