# Generated by Django 5.0.6 on 2026-03-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0020_roadmap_unique_active_roadmap_per_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pyq",
            constraint=models.UniqueConstraint(
                fields=("exam", "topic", "year", "marks"), name="unique_pyq_entry"
            ),
        ),
    ]
