# Generated by Django 5.0.6 on 2026-03-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0021_pyq_unique_pyq_entry"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pyq",
            name="unique_pyq_entry",
        ),
    ]
