# Generated by Django 5.0.6 on 2026-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0022_remove_pyq_unique_pyq_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyq",
            name="source_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
