# Generated by Django 5.0.6 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0023_pyq_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pyq",
            name="source_url",
            field=models.URLField(unique=True),
        ),
    ]
