# Generated by Django 5.0.6 on 2026-03-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0024_alter_pyq_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="roadmap.exam",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["order", "name"],
                "unique_together": {("exam", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="roadmap.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("subject", "parent", "name")},
        ),
        migrations.RemoveField(
            model_name="topic",
            name="exam",
        ),
    ]
