# Generated by Django 5.0.6 on 2026-03-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0025_subject_alter_topic_unique_together_topic_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_topics",
                to="roadmap.topic",
            ),
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="roadmap.topic",
                    ),
                ),
            ],
            options={
                "db_table": "subtopics",
                "ordering": ["order"],
                "unique_together": {("topic", "name")},
            },
        ),
    ]
