# Generated by Django 5.0.6 on 2026-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0026_alter_topic_parent_subtopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyq",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
