# Generated by Django 5.0.6 on 2026-03-16 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0027_pyq_question_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pyq",
            name="correct_answer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pyq",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pyq",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pyq",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Single Correct MCQ"),
                    ("msq", "Multiple Select"),
                    ("nat", "Numerical Answer"),
                    ("int", "Integer Answer"),
                    ("desc", "Descriptive"),
                ],
                default="mcq",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pyq",
            name="question_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserPYQAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField()),
                ("is_correct", models.BooleanField()),
                ("time_taken", models.IntegerField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pyq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="roadmap.pyq",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyq_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_pyq_attempts",
                "indexes": [
                    models.Index(
                        fields=["user", "pyq"], name="user_pyq_at_user_id_fa2723_idx"
                    )
                ],
            },
        ),
    ]
