# Generated by Django 5.0.6 on 2026-03-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0028_pyq_correct_answer_pyq_explanation_pyq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pyq",
            name="source_url",
            field=models.URLField(),
        ),
    ]
