# Generated by Django 5.0.6 on 2026-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0029_alter_pyq_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="weightage",
            field=models.FloatField(default=1.0),
        ),
    ]
