# Generated by Django 5.0.6 on 2026-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0030_alter_topic_weightage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pyq",
            name="explanation",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roadmaptopic",
            name="ai_explanation",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
