# Generated by Django 5.0.6 on 2026-05-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0031_alter_pyq_explanation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoadmapGenerationJob",
        ),
    ]
