# Generated by Django 5.0.6 on 2026-02-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="parent_document_id",
        ),
        migrations.AddField(
            model_name="document",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai_service.document",
            ),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("textbook", "Textbook"),
                    ("notes", "Notes"),
                    ("article", "Article"),
                    ("syllabus", "Syllabus"),
                    ("previous_paper", "Previous Year Paper"),
                ],
                db_index=True,
                default="notes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="exam_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
