# Generated by Django 5.0.6 on 2026-02-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0003_remove_document_parent_document_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["id"]},
        ),
    ]
