# Generated by Django 5.0.6 on 2026-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0004_alter_document_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagelog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
