# Generated by Django 5.0.6 on 2026-03-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0005_alter_aiusagelog_error_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="author",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="document",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="source_type",
            field=models.CharField(
                choices=[("upload", "Upload"), ("scraped", "Scraped")],
                db_index=True,
                default="upload",
                max_length=20,
            ),
        ),
    ]
