# Generated by Django 5.0.6 on 2026-05-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0008_remove_document_rag_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIUsageLog",
        ),
    ]
