# Generated by Django 5.0.6 on 2026-03-18 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roadmap", "0029_alter_pyq_source_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.CharField(max_length=255)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("marks", models.PositiveIntegerField(default=1)),
                ("negative_marks", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[("pyq", "PYQ"), ("llm", "LLM")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="roadmap.topic",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation_reason",
                    models.CharField(default="topic_practice", max_length=50),
                ),
                ("generation_topics", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("total_marks", models.IntegerField(default=0)),
                ("question_count", models.IntegerField(default=0)),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.exam",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_tests",
                        to="roadmap.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="mock_tests", to="mocktest.question"
                    ),
                ),
            ],
            options={
                "db_table": "mock_tests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("time_taken_minutes", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0.0)),
                ("total_marks", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("incorrect_answers", models.IntegerField(default=0)),
                ("unanswered", models.IntegerField(default=0)),
                (
                    "mock_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mocktest.mocktest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "test_attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(blank=True, max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("marks_obtained", models.FloatField(default=0.0)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mocktest.question",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="mocktest.testattempt",
                    ),
                ),
            ],
            options={
                "db_table": "answers",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["topic"], name="questions_topic_i_963006_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["source"], name="questions_source_1adf98_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="questions_difficu_8150ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["attempt"], name="answers_attempt_022a6b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("attempt", "question")},
        ),
    ]
