# Generated by Django 5.2.11 on 2026-02-05 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocktest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='questions_subject_7407ac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_type', 'difficulty'], name='questions_exam_ty_d227b3_idx'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(related_name='mock_tests', to='mocktest.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.question'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktest.mocktest'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mocktest.testattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
