# Generated by Django 5.0.6 on 2026-02-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktest", "0002_initial"),
        ("roadmap", "0004_roadmap_is_active_roadmap_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mocktest",
            name="generation_reason",
            field=models.CharField(default="adaptive", max_length=50),
        ),
        migrations.AddField(
            model_name="mocktest",
            name="generation_topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mocktest",
            name="roadmap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_tests",
                to="roadmap.roadmap",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="roadmap.exam",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="roadmap.roadmaptopic",
            ),
        ),
        migrations.AlterField(
            model_name="mocktest",
            name="exam_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mocktest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                db_index=True,
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["attempt"], name="answers_attempt_022a6b_idx"),
        ),
    ]
