# Generated by Django 5.0.6 on 2026-02-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mocktest", "0003_mocktest_generation_reason_and_more"),
        ("roadmap", "0005_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="topic_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="roadmap.topic",
            ),
        ),
    ]
